jokes=['Did you hear about the famous microbiologist who visited 30 different countries and spoke 6 languages? He was a man of many cultures.',
 'Biology is the only science in which multiplication is the same thing as division.',
 'What did the male stamen say to the female pistil? A: I like your "style."',
 'I wish I was adenine, then I could get paired with U.',
 'Did you just mutate for a stop codon? Because you\'re talking nonsense!',
 'Q: What is the fastest way to determine the sex of a chromosome? \nA: Pull down its genes!',
 'Q: Y\'all want to hear a Potassium joke? A: K',
 'I’ve never been a good swimmer, my DNA almost drowned in its gene pool.',
 'Why are tertiary structures selfish? Because the amino acids are all wrapped up in themselves.',
 'How can you better understand genetics in cold weather? Put your codon!',
  'Do you know why the geneticist went to dental school? He was looking for an oral high gene.']