import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")import pandas as pd
table = pd.read_csv("pivot.csv")