language: "en"


pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "LexicalSyntacticFeaturizer"

- name: "DIETClassifier"
  epochs: 150
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
